#!/bin/bash
#
# Startup script for icad-controller
#
# chkconfig: 345 85 15
# description: WatchmanAlerting iCAD Controller is a CAD-based remote incident dispatch service
# processname: icad-controller
# pidfile: /var/run/icad-controller.pid
# todo: If running service as non-compiled perl script rename icad-controller.pl -> icad-controller after copying to server

# Source function library.
. /etc/rc.d/init.d/functions

DESC="iCAD Control & Sync Service "
NAME=icad-controller
DAEMON="/usr/local/watchman-icad/bin/icad-controller"
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
LOCKFILE=/var/lock/subsys/$NAME

[ -x $DAEMON ] || exit 0

[ -f /etc/sysconfig/icad-controller ] && . /etc/sysconfig/icad-controller

RETVAL=0

stop() 
{
	echo -n "Stopping "$DESC
    killproc $NAME
    RETVAL=$?
	echo
    if [ $RETVAL -eq 0 ]; then
        rm -f $LOCKFILE
        rm -f $PIDFILE
    fi
}

start()
{
    echo -n "Starting "$DESC
	daemon $DAEMON $DAEMON_ARGS
	RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    
    return $RETVAL
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
  start)
	start
    ;;
  stop)
	stop
    ;;
  restart)
	restart
	;;
  condrestart)
    [ -e $LOCKFILE ] && restart
    RETVAL=$?
    ;;	
  status)
    status $NAME
    ;;
  *)
  echo $DESC" ["$NAME"]"
  echo "Usage: "$1" {start|stop|restart|condrestart|status}"
  exit 1
esac

exit $?